domains:
    - pelayanan
php_version: "8.4"
framework: laravel
framework_version: "12"
secured: true
services:
    - mysql
    - redis
    - mailpit
    - chromium-service:
        name: chromium-service
        image: docker.io/browserless/chrome:latest
        ports:
            - 3000:3000
        description: Chrome Headless Service
workers:
    - queue
    - schedule
    - vite
