# docker-compose.prod.yml (Untuk SERVER PRODUKSI)
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pelayanan_dokumen_app
    restart: always # Auto-start jika server mati
    ports:
      - "80:80" # Trafik web langsung masuk
      - "443:443"
    volumes:
      - db_data:/var/lib/mysql
      - caddy_data:/data
      - caddy_config:/config
    env_file:
      - .env.production # <-- Membaca dari file env khusus server

volumes:
  db_data:
  caddy_data:
  caddy_config:
