[supervisord]
nodaemon=true
user=root
logfile=/var/log/supervisor/supervisord.log

[program:mysql]
command=/usr/bin/mysqld --user=mysql --console --skip-name-resolve --skip-networking=0 --bind-address=0.0.0.0
autostart=true
autorestart=true
priority=1

[program:redis]
command=redis-server
autostart=true
autorestart=true

[program:php-app]
command=frankenphp run --config /etc/caddy/Caddyfile
autostart=true
autorestart=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[unix_http_server]
file=/var/run/supervisor.sock   ; path ke socket file

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///var/run/supervisor.sock ; hubungkan ke socket di atas
