// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetChimeDataURL(arg1:string):Promise<string>;

export function GetConfig():Promise<main.AppConfig>;

export function GetMode():Promise<string>;

export function IsAudioAvailable():Promise<boolean>;

export function OpenDisplay():Promise<number>;

export function PlayCallAudio(arg1:main.CallPayload):Promise<string>;

export function PlayTestAudio():Promise<string>;

export function SetFullscreen(arg1:boolean):Promise<void>;

export function SetHomeWindow():Promise<void>;

export function SetStaffWindow():Promise<void>;

export function SynthSpeech(arg1:string,arg2:string,arg3:number,arg4:number):Promise<string>;

export function UnlockAudio():Promise<string>;
