// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetChimeDataURL(arg1) {
  return window['go']['main']['App']['GetChimeDataURL'](arg1);
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetMode() {
  return window['go']['main']['App']['GetMode']();
}

export function IsAudioAvailable() {
  return window['go']['main']['App']['IsAudioAvailable']();
}

export function OpenDisplay() {
  return window['go']['main']['App']['OpenDisplay']();
}

export function PlayCallAudio(arg1) {
  return window['go']['main']['App']['PlayCallAudio'](arg1);
}

export function PlayTestAudio() {
  return window['go']['main']['App']['PlayTestAudio']();
}

export function SetFullscreen(arg1) {
  return window['go']['main']['App']['SetFullscreen'](arg1);
}

export function SetHomeWindow() {
  return window['go']['main']['App']['SetHomeWindow']();
}

export function SetStaffWindow() {
  return window['go']['main']['App']['SetStaffWindow']();
}

export function SynthSpeech(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['SynthSpeech'](arg1, arg2, arg3, arg4);
}

export function UnlockAudio() {
  return window['go']['main']['App']['UnlockAudio']();
}
